### ISSUE TITLE
Attribute 'threshold' not being read

### ISSUE THREAD

**Issue by brmagalis** [Omer80/NetStruct_python#1]
Hello!

I am trying to run the script in a virtual environment with the older version of python (2.7), which may have something to do with it, but I am receiving the following error and am not familiar enough with python to run with it:

(temp-python)$ python2 netstruct.py -c netstruct_infile.hdf5 0 1 0.05 2
Processing command:  netstruct_infile.hdf5 0 1 0.05 2 None
Running command:  netstruct_infile.hdf5 0.0 1.0 0.05 2 Community_Detection_Results
Output filename:  Community_Detection_Results
Traceback (most recent call last):
  File "netstruct.py", line 497, in <module>
    main(args)
  File "netstruct.py", line 400, in main
    ,algorithm_num,args.loopGDmat_results)
  File "netstruct.py", line 229, in loopGDmat
    graph = FindCommunities(data_fname,threshold,algorithm_num)
  File "netstruct.py", line 167, in FindCommunities
    matx=stats.threshold(GDmatrix, threshmin=threshold,newval=0) # Creates an adjacency matrix with a threshold applied to GDmatrix (i.e. all values below the threshold are taken to be 0)
AttributeError: 'module' object has no attribute 'threshold'

**Comment by CheWeiChang1992** [comment]
Hello,
I also confronted the same error when trying to use NetStruct.

I found that the problem is actually due to the version of **scipy**.
The 'threshold' has been deprecated since **scipy 0.17**!
**You can try to downgrade your scipy to version 0.16** like this:
`sudo python -m pip install 'scipy>0.15,<0.17' --force-reinstall`

It will be good to put this issue in the user manual

Cheers!
